security:
    encoders:
        App\Domain\Models\User:
            algorithm: bcrypt
    providers:
        doctrine:
            entity:
                class: App\Domain\Models\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        main:
#            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login_check
        secured_area:

            provider: doctrine

            # Turn on anonymous for testings need.
            anonymous: ~

            guard:
                entry_point: App\Security\Guard\LoginFormAuthenticator
                authenticators: [App\Security\Guard\LoginFormAuthenticator,App\Security\Guard\GoogleAuthenticator,App\Security\Guard\FacebookAuthenticator]
#
            logout:
                path:   /logout
#                target: /
#                delete_cookies:
#                    a: { path: null, domain: null }
#                    b: { path: null, domain: null }
##                handlers: [some.service.id, another.service.id]
#                success_handler: some.service.id

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/saisir-article, roles: [ ROLE_NATURALIST ], methods: [GET, POST] }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_NATURALIST: ROLE_USER
        ROLE_ADMIN:      ROLE_NATURALIST